version: '3.1'
services:
  postgresql:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=Wryip
      - POSTGRES_USER=postgres
      - POSTGRES_DB=orderservicedb
  springbootapp:
    build: ./
    container_name: springbootapp
    image: springbootapp:latest
    ports:
      - 8080:8080
    environment:
      - DB_SERVER=postgres
      - POSTGRES_DB=orderservicedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Wryip
    depends_on:
      - postgresql
